name: Dependabot automation

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b  # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-approve for Dependabot PRs
        if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
        run: gh pr review --approve "${PR_URL}"

      - name: Enable auto-approve for Dependabot PRs
        if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
        run: gh pr merge --squash --auto "${PR_URL}" || gh pr merge --merge --auto "${PR_URL}" || gh pr merge --rebase --auto "${PR_URL}"
